# Generated by Django 4.1.3 on 2022-11-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="claimamount",
            options={"verbose_name_plural": "claim amount"},
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={"verbose_name_plural": "staff"},
        ),
    ]
