# Generated by Django 4.1.3 on 2022-11-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0002_alter_claimamount_options_alter_staff_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_viewer",
            new_name="can_add_claim",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_creator",
            new_name="can_approve_calm",
        ),
    ]
