# Generated by Django 4.1.3 on 2022-11-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0003_rename_is_viewer_user_can_add_claim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimapprover",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
