# Generated by Django 4.1.3 on 2022-11-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_claimapprover_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
