# Generated by Django 4.1.3 on 2022-11-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_claim_location_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
